# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(default=datetime.date.today)),
                ('sender', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(default=datetime.date.today)),
                ('sender', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('apply_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('fee_amt', models.FloatField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='FeesInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_fees_amt', models.FloatField()),
                ('balance_fees_amt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='management.Management')),
            ],
        ),
        migrations.AddField(
            model_name='feesdetail',
            name='fees_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_detail', to='management.FeesInformation'),
        ),
        migrations.AddField(
            model_name='event',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='management.Management'),
        ),
        migrations.AddField(
            model_name='circular',
            name='circular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circular', to='management.Management'),
        ),
    ]
