# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circular',
            old_name='circular',
            new_name='management',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='events',
            new_name='management',
        ),
        migrations.RenameField(
            model_name='feesdetail',
            old_name='fees_details',
            new_name='fees_information',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='planner',
            new_name='management',
        ),
    ]
