# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20170917_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='management',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
