# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170918_0225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
