# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('venue', models.CharField(max_length=64)),
                ('date', models.DateField(default=datetime.date.today)),
                ('incharge', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='management.Management')),
            ],
        ),
    ]
