# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdetail',
            name='fees_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_detail', to='management.FeesInformation'),
        ),
    ]
