# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateField(default=datetime.date.today)),
                ('year_of_pass', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=32)),
                ('institute', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=32)),
                ('percentage', models.FloatField()),
                ('year_of_passedout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(max_length=32)),
                ('community', models.CharField(max_length=10)),
                ('caste', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=32)),
                ('mother_tongue', models.CharField(max_length=32)),
                ('place_of_birth', models.CharField(max_length=32)),
                ('financial_category', models.CharField(choices=[('Self', 'Self'), ('Loan', 'Loan')], max_length=4)),
                ('admission_type', models.CharField(max_length=32)),
                ('admission_category', models.CharField(max_length=32)),
                ('primary_address', models.TextField()),
                ('secondary_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_group', models.CharField(max_length=5)),
                ('physically_challenged', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('eye_colour', models.CharField(max_length=10)),
                ('eye_sight', models.CharField(max_length=10)),
                ('mole', models.CharField(max_length=32)),
                ('scar', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=127)),
                ('mother_name', models.CharField(max_length=127)),
                ('income', models.FloatField(verbose_name='Income')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('roll_no', models.CharField(max_length=127)),
                ('profile', models.ImageField(upload_to=b'', verbose_name='student_image')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='dob')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.Batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.Department')),
                ('fees_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='management.FeesInformation')),
                ('general_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.GeneralInformation')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='management.Management')),
                ('medical_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.MedicalInformation')),
                ('parent_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.ParentsDetail')),
            ],
        ),
        migrations.AddField(
            model_name='educationalinformation',
            name='educational_informations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_informations', to='student.Student'),
        ),
    ]
