# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateField()),
                ('year_of_pass', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=32)),
                ('institute', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=32)),
                ('percentage', models.FloatField()),
                ('year_of_passedout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_group', models.CharField(max_length=5)),
                ('physically_challenged', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('eye_colour', models.CharField(max_length=10)),
                ('eye_sight', models.CharField(max_length=10)),
                ('mole', models.CharField(max_length=32)),
                ('scar', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=127)),
                ('mother_name', models.CharField(max_length=127)),
                ('income', models.FloatField(verbose_name='Income')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='dob')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(max_length=32)),
                ('community', models.CharField(max_length=10)),
                ('caste', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=32)),
                ('mother_tongue', models.CharField(max_length=32)),
                ('place_of_birth', models.CharField(max_length=32)),
                ('financial_category', models.CharField(choices=[('Self', 'Self'), ('Loan', 'Loan')], max_length=4)),
                ('admission_type', models.CharField(max_length=32)),
                ('admission_category', models.CharField(max_length=32)),
                ('primary_address', models.TextField()),
                ('secondary_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('roll_no', models.CharField(max_length=127)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Batch')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Department')),
                ('medical_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.MedicalInformation')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.ParentDetails')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.PersonalDetails')),
            ],
        ),
        migrations.AddField(
            model_name='educationalinformations',
            name='educational_informations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_informations', to='student.Student'),
        ),
    ]
