# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(default='../media/default-user-image.png', upload_to='../media', verbose_name='student_image'),
        ),
    ]
