# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170917_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('apply_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('fee_amt', models.FloatField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='FeesInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_fees_amt', models.FloatField()),
                ('balance_fees_amt', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='fees_information',
        ),
        migrations.AddField(
            model_name='feesinformation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_information', to='student.Student'),
        ),
        migrations.AddField(
            model_name='feesdetail',
            name='fees_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_detail', to='student.FeesInformation'),
        ),
    ]
