# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('academics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.Academic')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result', to='academics.Academic')),
            ],
        ),
        migrations.CreateModel(
            name='InternalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InternalExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=50)),
                ('min_mark', models.IntegerField()),
                ('max_mark', models.IntegerField()),
                ('obtained_mark', models.IntegerField()),
                ('first_mark', models.IntegerField()),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=5)),
                ('internal_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_exam_subject', to='academics.InternalExam')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMarkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_mark_detail', to='academics.Academic')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64)),
                ('book_id', models.CharField(max_length=32)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('renewal_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('fine_amt', models.FloatField()),
                ('status', models.CharField(choices=[('ISSUED', 'ISSUED'), ('RENEWED', 'RENEWED'), ('RETURNED', 'RETURNED')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_status', to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.IntegerField()),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=4)),
                ('grade_point', models.IntegerField()),
                ('credit_point', models.IntegerField()),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=5)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subject', to='academics.ExamResult')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], max_length=20)),
                ('year', models.IntegerField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_month', to='academics.Attendance')),
            ],
        ),
        migrations.AddField(
            model_name='internalexam',
            name='mark_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_exam', to='academics.InternalMarkDetail'),
        ),
    ]
