# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='acadamic',
            new_name='academics',
        ),
    ]
