# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20170917_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingmonth',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_month', to='academics.Attendance'),
        ),
    ]
