# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_examresult_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
    ]
