# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_examresult_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='academics',
        ),
        migrations.AddField(
            model_name='academic',
            name='exam_result',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='academics.ExamResult'),
        ),
    ]
