# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_auto_20170923_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='exam_result',
        ),
        migrations.AlterField(
            model_name='examresult',
            name='academic',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.Academic'),
        ),
    ]
