# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_auto_20170923_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='academic',
        ),
    ]
