# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_examresult_academic'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='academic_data',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.Academic'),
        ),
    ]
