# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_examresult_academic_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='academic_data',
            new_name='academics',
        ),
    ]
