# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_auto_20170923_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='academics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exam_results', serialize=False, to='academics.Academic'),
        ),
    ]
