# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_auto_20170923_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmarkdetail',
            name='academics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_mark_detail', to='academics.Academic'),
        ),
    ]
